# Generated by Django 5.1.3 on 2024-12-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='ComplaintTable',
        ),
    ]
