# Generated by Django 5.1.3 on 2024-12-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_turf_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttable',
            name='TURF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.turf'),
            preserve_default=False,
        ),
    ]
