# Generated by Django 5.1.3 on 2024-12-21 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_equipmenttable_turf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='TURF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.turf'),
        ),
    ]
